// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MimibotWebserver.Models;

namespace MimibotWebserver.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190228030039_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MimibotWebserver.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answers");

                    b.Property<string>("Questions");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MimibotWebserver.Models.Mark", b =>
                {
                    b.Property<string>("MarkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<string>("MarkValue");

                    b.Property<string>("Question");

                    b.Property<string>("UserId");

                    b.HasKey("MarkId");

                    b.ToTable("Mark");
                });

            modelBuilder.Entity("MimibotWebserver.Models.Sms", b =>
                {
                    b.Property<string>("SmsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Details");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Relationship");

                    b.Property<string>("UserId");

                    b.HasKey("SmsId");

                    b.ToTable("Sms");
                });

            modelBuilder.Entity("MimibotWebserver.Models.Speech", b =>
                {
                    b.Property<string>("SpeechId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DateTime");

                    b.Property<string>("Keyword");

                    b.Property<string>("Sentiment");

                    b.Property<string>("SpeechDetails");

                    b.Property<string>("Tags");

                    b.Property<string>("UserId");

                    b.HasKey("SpeechId");

                    b.ToTable("Speechs");
                });

            modelBuilder.Entity("MimibotWebserver.Models.Upload", b =>
                {
                    b.Property<string>("UploadId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("SongLink");

                    b.Property<string>("UserId");

                    b.HasKey("UploadId");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("MimibotWebserver.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FatherNo");

                    b.Property<string>("MotherNo");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
